<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BusinessSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('business')->insert([
            ["name" => "Công ty cổ phần chứng khoán VPS","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-chung-khoan-vps-5ff1a3dc0a075.jpg","industry" => "Kinh doanh/ Bán hàng","location" => "2A Đại Cồ Việt, Hai Bà Trưng, Hà Nội","country" => "Việt Nam","province" => "Thành phố Hà Nội","employees_number" => 1200,"website" => "https://www.vps.com.vn/","contact_email" => "ckvps@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "CÔNG TY TNHH CÔNG NGHỆ CAO VIỆT TRUNG","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/FhCJykjpy7sv8hYzJe00msXdgHx6J6G5_1653355299____c8601340891bf0b1aa34bdccaaee0375.jpg","industry" => "Kinh doanh/ Bán hàng","location" => "Số B19 - 17 Khu B, KĐT mới Geleximco, Lê Trọng Tấn, Dương Nội, Hà Đông, Hà Nội","country" => "Việt Nam","province" => "Thành phố Hà Nội","employees_number" => 100,"website" => "https://www.cambienviet.vn/","contact_email" => "viettrung@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "FPT Information System","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/fpt-information-system-5c7cac4be5cf1_rs.jpg","industry" => "Công nghệ thông tin","location" => "Tầng 22 toà nhà Keangnam Landmark 72, E6 Phạm Hùng, Nam Từ Liêm, Hà Nội","country" => "Việt Nam","province" => "Thành phố Hà Nội","employees_number" => 5300,"website" => "https://www.fis.com.vn/","contact_email" => "contact@fpt.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "Công ty Cổ phần Công nghệ Sen Đỏ","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-cong-nghe-sen-do-6357a4207d231.jpg","industry" => "Kinh doanh/ Bán hàng","location" => "Tầng 9, Tòa nhà Oriental, 324 Tây Sơn, Đống Đa, Hà Nội","country" => "Việt Nam","province" => "Thành phố Hà Nội","employees_number" => 1000,"website" => "https://www.sendo.vn/","contact_email" => "sendo@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "CÔNG TY CỔ PHẦN ĐẦU TƯ & THƯƠNG MẠI QUỐC TẾ TÂM VIỆT","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/MgFfmZDcHYEo4D7CIs4fgL7ezBIfssjh_1658741919____af826fe24fde3512784e8a9f1f85c057.jpg","industry" => "Kinh doanh/ Bán hàng","location" => "ngõ 22 Đường Mạc Thái Tổ, Yên Hòa, Cầu Giấy, Hà Nội","country" => "Việt Nam","province" => "Thành phố Hà Nội","employees_number" => 1000,"website" => "https://duoctamviet.com.vn/","contact_email" => "tamviet@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "CÔNG TY TNHH ALI LOGISTICS VIỆT NAM","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-tnhh-ali-logistics-viet-nam-62a7f0b79767d.jpg","industry" => "Kinh doanh/Bán hàng","location" => "168 TRUNG KINH,CẦU GIẤY, HÀ NỘI","country" => "Việt Nam","province" => "Thành phố Hà Nội","employees_number" => 1000,"website" => "https://orderthangloi.com/","contact_email" => "thangloi@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "Công ty Cổ phần Giáo dục & Đào tạo IMAP Việt Nam","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-giao-duc-dao-tao-imap-viet-nam-5da97e1f22484.jpg","industry" => "Hành chính/Văn phòng","location" => "14 Trần Kim Xuyến, Yên Hoà,  Cầu Giấy, Hà Nội","country" => "Việt Nam","province" => "Thành phố Hà Nội","employees_number" => 100,"website" => "https://imap.edu.vn/","contact_email" => "imapedu@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "Công Ty TNHH Thiết Bị Khoa Học Việt Anh","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-tnhh-thiet-bi-khoa-hoc-viet-anh-5f7d41fd236f9.jpg","industry" => "Kinh doanh/Bán hàng","location" => "Số 2 Lô 3A Khu đô thị Trung Yên, Trung Hoà, Cầu Giấy, Hà Nội","country" => "Việt Nam","province" => "Thành phố Hà Nội","employees_number" => 100,"website" => "https://vietanhco.com.vn/","contact_email" => "vietanh@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "CÔNG TY TNHH DCORP TOÀN CẦU","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-tnhh-dcorp-toan-cau-602dcf7ca2899.jpg","industry" => "Kinh doanh/Bán hàng","location" => "Căn hộ số 00.22, tầng trệt, Số 19 đường Tố Hữu, Phường Thủ Thiêm, Thành phố Thủ Đức, Thành phố Hồ Chí Minh","country" => "Việt Nam","province" => "Thành phố Hồ Chí Minh","employees_number" => 100,"website" => "https://kodo.vn/","contact_email" => "kodo@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "CÔNG TY TNHH BẢO HIỂM NHÂN THỌ PRUDENTIAL VIỆT NAM","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-tnhh-bao-hiem-nhan-tho-prudential-viet-nam-kenh-kinh-doanh-qua-dien-thoai-5fabb2b39d30f.jpg","industry" => "Bảo hiểm","location" => "Toà nhà Prudential Tầng 05, 02-04 Bến Cần Giuộc, Quận 8, TPHCM","country" => "Việt Nam","province" => "Thành phố Hồ Chí Minh","employees_number" => 1000,"website" => "https://www.prudential.com.vn/vi/","contact_email" => "prudential@gmai.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "Công Ty Cổ Phần Đất Xanh Miền Trung","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-dat-xanh-mien-trung-62f31d414ed86.jpg","industry" => "Kinh doanh/Bán hàng","location" => "52-54 Võ Văn Kiệt, Phường An Hải Đông, Quận Sơn Trà, Thành Phố Đà Nẵng","country" => "Việt Nam","province" => "Thành phố Đà Nẵng","employees_number" => 800,"website" => "https://datxanhmientrung.com/","contact_email" => "datxanh@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "Công Ty Cổ Phần Truyền Thông Kim Cương","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-truyen-thong-kim-cuong-6110e386df0ef.jpg","industry" => "Kinh doanh/Bán hàng","location" => "215 Phan Đăng Lưu, Khuê Trung, Cẩm Lệ, Đà Nẵng","country" => "Việt Nam","province" => "Thành phố Đà Nẵng","employees_number" => 500,"website" => "https://callcenter.vn/","contact_email" => "kimcuong@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "CÔNG TY CỔ PHẦN THƯƠNG MẠI VÀ DỊCH VỤ KHO VẬN PHÚ HƯNG","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/cong-ty-co-phan-thuong-mai-va-dich-vu-kho-van-phu-hung-636e09cfbd5f8.jpg","industry" => "Kinh doanh/Bán hàng","location" => "Số 49 Đinh Tiên Hoàng, Phường Hoàng Văn Thụ, Quận Hồng Bàng, Thành phố Hải Phòng","country" => "Việt Nam","province" => "Thành phố Hải Phòng","employees_number" => 1000,"website" => "http://phuhungjsc-eco.com/","contact_email" => "phuhung@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["name" => "Công ty cổ phần thời trang Xinh Xinh","business_logo" => "https://cdn-new.topcv.vn/unsafe/140x/filters:format(webp)/https://static.topcv.vn/company_logos/L634VwkVXfBUjOVGmYpTD2BSqPbUksm7_1664254283____0f63ac9d31189fb9cfa4708e4d2ec2ab.jpg","industry" => "Kinh doanh/Bán hàng","location" => "11 Phạm Minh Đức , Máy Tơ , Ngô Quyền , Hải Phòng","country" => "Việt Nam","province" => "Thành phố Hải Phòng","employees_number" => 25,"website" => "https://thoitrangxinh.net/","contact_email" => "xinhxinh@gmail.com", "created_at" => Carbon::now(), "updated_at" => Carbon::now()]
        ]);
    }
}
