<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobPostingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('job_postings')->insert([
            ["business_id" => 1,"title" => "Thực Tập Sinh Tư Vấn Đầu Tư Chứng Khoán","description" => "<p><strong>3 lý do để gia nhập công ty</strong></p>\n<p>&nbsp; 1. Dẫn đầu thị trường: Công ty này luôn đứng đầu trong việc định hình và thay đổi ngành công nghiệp, tạo ra cơ hội để tham gia vào các dự án tiên tiến và đổi mới.</p>
                <p>&nbsp; 2. Cơ hội thử thách và phát triển bản thân: Tại đây, tôi được khích lệ và hỗ trợ để đối mặt với những thách thức mới, từ đó phát triển kỹ năng và nâng cao khả năng cá nhân.</p>
                <p>&nbsp; 3. Môi trường làm việc đa dạng và sáng tạo: Công ty tạo điều kiện cho sự đa dạng về ý kiến, sự sáng tạo và cơ hội hợp tác với những người tài năng từ khắp nơi trên thế giới.</p>
                <p><strong>Mô tả công việc</strong></p>
                <p>&nbsp; Trách nhiệm chính của vị trí này tập trung vào việc [mô tả chi tiết về nhiệm vụ, trách nhiệm, và các hoạt động cụ thể]. Đây là một cơ hội tuyệt vời để [nhấn mạnh cơ hội phát triển, ảnh hưởng của công việc đối với mục tiêu của công ty, hoặc lợi ích cá nhân].</p>","salary" => 5000000,"industry" => "Kinh doanh","field" => "Chứng khoán","internship_duration" => 2,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 16,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 1,"title" => "Thực Tập Sinh Quản lý nhân sự","description" => "<p><strong>Kiểm soát công, OT, nghỉ vắng của nhân viên</strong></p>\n<p>Quản lý và kiểm soát chặt chẽ thông tin về giờ làm việc, giờ làm thêm (OT) và các thông tin vắng mặt của nhân viên để đảm bảo tính chính xác và minh bạch trong quản lý nhân sự.</p>
                <p><strong>Thực hiện các công việc liên quan đến tính lương</strong></p>
                <p>Chịu trách nhiệm thực hiện các hoạt động liên quan đến tính toán lương như xác định tiền lương cơ bản, các khoản thưởng, phụ cấp và khấu trừ theo quy định của công ty.</p>
                <p><strong>Thực hiện các báo cáo lương theo yêu cầu của các phòng ban</strong></p>
                <p>Chuẩn bị và cung cấp thông tin lương theo yêu cầu của các phòng ban khác nhau, đảm bảo rằng thông tin được cung cấp là chính xác và kịp thời để hỗ trợ quyết định và hoạt động của họ.</p>","salary" => 7000000,"industry" => "Nhân sự","field" => "Chứng khoán","internship_duration" => 8,"internship_method" => "online","internship_type" => "parttime","recruitment_number" => 20,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 1,"title" => "Thực tập Sinh Bảo mật CNTT","description" => "<p><strong>Tham gia các hoạt động quản lý và điều hành Bảo mật CNTT hàng ngày</strong></p>\n<p>Thực hiện các nhiệm vụ hàng ngày liên quan đến quản lý và điều hành an ninh thông tin và công nghệ thông tin (CNTT), đảm bảo tính an toàn và bảo mật của hệ thống.</p>
                <p><strong>Tham gia thử nghiệm thâm nhập và dò quét lỗ hổng</strong></p>
                <p>Tham gia các hoạt động thử nghiệm để đánh giá và phát hiện các lỗ hổng bảo mật trong hệ thống, từ đó tăng cường các biện pháp phòng ngừa và bảo mật.</p>
                <p><strong>Báo cáo cho quản lý các sự cố do xâm nhập mạng và / hoặc các nỗ lực tấn công</strong></p>
                <p>Ghi nhận và báo cáo kịp thời các sự cố xâm nhập mạng và các nỗ lực tấn công đối với hệ thống, cung cấp thông tin chi tiết để hỗ trợ quản lý đưa ra các biện pháp can thiệp và ngăn chặn.</p>","salary" => 4000000,"industry" => "Công nghệ thông tin","field" => "Chứng khoán","internship_duration" => 2,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 20,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 2,"title" => "Thực tập Sinh Tư Vấn Giải Pháp CN ","description" => "<p><strong>Ứng dụng các nền tảng xã hội để Nghiên cứu thị trường tìm kiếm khách hàng cũng như quảng bá sản phẩm</strong></p>\n<p>Sử dụng các nền tảng xã hội nhằm nghiên cứu thị trường, tìm kiếm và tiếp cận khách hàng tiềm năng, đồng thời tận dụng để quảng bá sản phẩm/dịch vụ.</p>
                <p><strong>Thực hiện cold call/gửi email giới thiệu công ty và sản phẩm/dịch vụ đến các khách hàng tiềm năng</strong></p>
                <p>Tiến hành cold call và gửi email giới thiệu chi tiết về công ty cũng như sản phẩm/dịch vụ đến các đối tác tiềm năng để tạo cơ hội gặp gỡ và thúc đẩy hợp tác.</p>
                <p><strong>Nhận biết, nắm bắt nhu cầu của khách hàng để từ đó giới thiệu các dịch vụ phù hợp</strong></p>
                <p>Phân tích và hiểu rõ nhu cầu của khách hàng, từ đó đề xuất các dịch vụ phù hợp và tối ưu để đáp ứng mong muốn của họ.</p>
                <p><strong>Giải quyết các vấn đề, vướng mắc của khách hàng để luôn đảm bảo được sự tin cậy, hài lòng của khách hàng.</strong></p>
                <p>Chủ động xử lý và giải quyết các vấn đề, khúc mắc của khách hàng, đảm bảo họ luôn cảm thấy hài lòng và tin tưởng vào sản phẩm/dịch vụ.</p>
                <p><strong>Thực hiện các hoạt động chăm sóc khách hàng, quản lý cơ sở dữ liệu khách hàng trước và sau bán hàng</strong></p>
                <p>Tiến hành các hoạt động chăm sóc khách hàng, duy trì và quản lý cơ sở dữ liệu thông tin của khách hàng để tạo môi trường giao dịch lâu dài và đáng tin cậy.</p>","salary" => null,"industry" => "Tư vấn","field" => "Y tế","internship_duration" => 7,"internship_method" => "hybrid","internship_type" => "parttime","recruitment_number" => 24,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 2,"title" => "Thực tập kế toán","description" => "<p><strong>Tiếp nhận thông tin, lập chứng từ hồ sơ kế toán</strong></p>\n<p>Chịu trách nhiệm tiếp nhận thông tin, xử lý và lập các chứng từ trong hồ sơ kế toán, đảm bảo tính chính xác và đầy đủ của dữ liệu.</p>
                <p><strong>Theo dõi hạch toán, định khoản lên sổ sách</strong></p>
                <p>Thực hiện việc theo dõi và hạch toán các giao dịch, định khoản chính xác lên sổ sách kế toán theo quy định của công ty và pháp luật.</p>
                <p><strong>Cân đối doanh thu chi phí, lên báo cáo tài chính</strong></p>
                <p>Thực hiện cân đối và kiểm tra tính đúng đắn giữa doanh thu và chi phí, từ đó lập báo cáo tài chính theo chuẩn mực và quy định hiện hành.</p>
                <p><strong>Kê khai thuế, quyết toán thuế cuối quý, cuối năm</strong></p>
                <p>Chịu trách nhiệm kê khai thuế đúng hạn, thực hiện quyết toán thuế cuối quý và cuối năm theo quy định của cơ quan thuế để đảm bảo tuân thủ pháp luật và tránh phát sinh vi phạm.</p>","salary" => 8000000,"industry" => "Kế toán","field" => "Y tế","internship_duration" => 6,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 16,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 2,"title" => "Thực tập Kinh doanh","description" => "<p><strong>Tìm kiếm, tiếp cận các Khách hàng Doanh nghiệp (KHDN) tiềm năng</strong></p>\n<p>Tìm kiếm và tiếp cận các doanh nghiệp có tiềm năng, xác định và phát triển mối quan hệ với họ để tạo cơ hội hợp tác và tăng doanh số bán hàng.</p>
                <p><strong>Tư vấn và hỗ trợ khách hàng sử dụng sản phẩm</strong></p>
                <p>Cung cấp tư vấn chi tiết và hỗ trợ cho khách hàng trong việc sử dụng sản phẩm/dịch vụ, giúp họ tận dụng tối đa các tính năng và hiệu quả của sản phẩm.</p>
                <p><strong>Hoàn tất hồ sơ khách hàng</strong></p>
                <p>Hoàn tất các thủ tục và hồ sơ liên quan đến thông tin khách hàng, đảm bảo tính chính xác và đầy đủ để quản lý thông tin khách hàng hiệu quả.</p>
                <p><strong>Duy trì quan hệ, chăm sóc và theo dõi khách hàng</strong></p>
                <p>Duy trì mối quan hệ tốt đẹp với khách hàng, tiếp tục chăm sóc và theo dõi họ sau khi giao dịch được thực hiện để đảm bảo họ hài lòng và tiếp tục hợp tác trong tương lai.</p>","salary" => 5000000,"industry" => "Kinh doanh","field" => "Y tế","internship_duration" => 1,"internship_method" => "online","internship_type" => "parttime","recruitment_number" => 15,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 3,"title" => "Thực tập sinh .NET","description" => "<p><strong>Tiếp nhận, phân tích yêu cầu từ cán bộ tư vấn nghiệp vụ, hỗ trợ giải pháp cho các yêu cầu chức năng</strong></p>\n<p>Chịu trách nhiệm tiếp nhận và phân tích các yêu cầu từ cán bộ tư vấn nghiệp vụ, cung cấp hỗ trợ giải pháp cho các yêu cầu chức năng.</p>
                <p><strong>Thiết kế, lập trình, làm tài liệu và sửa lỗi chương trình</strong></p>
                <p>Thiết kế, viết mã, tạo tài liệu và xử lý lỗi trong quá trình phát triển chương trình theo yêu cầu và tiêu chuẩn xác định.</p>
                <p><strong>Nghiên cứu các công nghệ và sản phẩm mới và đề xuất ứng dụng vào thực tiễn.</strong></p>
                <p>Tìm hiểu và đề xuất việc áp dụng các công nghệ và sản phẩm mới vào thực tế, nâng cao hiệu suất và hiệu quả của công việc.</p>
                <p><strong>Đào tạo, hỗ trợ các thành viên mới trong team</strong></p>
                <p>Hỗ trợ và đào tạo các thành viên mới trong nhóm để họ có thể nhanh chóng hòa nhập và đạt được hiệu quả công việc cao.</p>
                <p><strong>Tham gia các dự án phát triển phần mềm với các khách hàng lớn của Công ty</strong></p>
                <p>Tham gia hoạt động phát triển phần mềm trong các dự án với các khách hàng lớn của công ty, đảm bảo đạt được các mục tiêu chất lượng và tiến độ.</p>","salary" => 4000000,"industry" => "Công nghệ thông tin","field" => "Design","internship_duration" => 10,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 18,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 3,"title" => "Thực tập Backend Developer (NodeJS /NestJS)","description" => "<p><strong>Tham gia xây dựng các platforms có khả năng scaling tốt, performance cao, mang lại trải nghiệm tốt cho khách hàng.</strong></p>\n<p>Tham gia vào quá trình xây dựng các nền tảng có khả năng mở rộng tốt, hiệu suất cao, đem lại trải nghiệm tốt nhất cho khách hàng.</p>
                <p><strong>Giải quyết các bài toán về Data Realtime, A/B Testing, các nghiệp vụ phức tạp.</strong></p>
                <p>Tìm giải pháp cho các vấn đề về dữ liệu thời gian thực, thử nghiệm A/B, và các vấn đề liên quan đến các nghiệp vụ phức tạp.</p>
                <p><strong>Thiết kế Domain Driven Design, triển khai Clean Code, Unit Test, Deployment và đảm bảo an toàn hệ thống.</strong></p>
                <p>Thực hiện thiết kế theo Domain Driven Design, triển khai Clean Code, thực hiện Unit Test, triển khai và đảm bảo an toàn cho hệ thống.</p>","salary" => 0,"industry" => "Công nghệ thông tin","field" => "Design","internship_duration" => 8,"internship_method" => "hybrid","internship_type" => "parttime","recruitment_number" => 18,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 3,"title" => "Thực tập Frontend Developer (Angular/ ReactJS )","description" => "<p><strong>Hỗ trợ tiếp nhận, phân tích yêu cầu từ các stakeholders cùng Business Analyst Team.</strong></p>\n<p>Đồng hành và hỗ trợ quá trình tiếp nhận và phân tích yêu cầu từ các bên liên quan cũng như nhóm Business Analyst, đảm bảo hiểu đúng và đầy đủ.</p>
                <p><strong>Nghiên cứu các công nghệ mới, các best practices và đề xuất ý tưởng cải tiển sản phẩm.</strong></p>
                <p>Tìm hiểu về các công nghệ mới, các phương pháp tốt nhất và đưa ra các ý tưởng cải tiến sản phẩm phù hợp.</p>
                <p><strong>Lên kế hoạch doanh số và lợi nhuận tháng/ tuần/ ngày</strong></p>
                <p>Xây dựng và quản lý kế hoạch doanh số và lợi nhuận theo từng thời kỳ để đảm bảo hoạt động kinh doanh hiệu quả.</p>
                <p><strong>Quản lý chi phí khuyến mãi theo chỉ tiêu yêu cầu</strong></p>
                <p>Điều chỉnh và quản lý chi phí khuyến mãi theo các chỉ tiêu và yêu cầu được đặt ra, đảm bảo tối ưu hóa hiệu quả chi phí.</p>
                <p><strong>Thực hiện các công việc khác theo yêu cầu của cấp trên</strong></p>
                <p>Hoàn thành các nhiệm vụ khác theo yêu cầu và chỉ đạo từ cấp trên để hỗ trợ hoạt động của công ty.</p>","salary" => 5000000,"industry" => "Công nghệ thông tin","field" => "Design","internship_duration" => 9,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 16,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 4,"title" => "Thực tập lập kế hoạc kinh doanh","description" => "<p><strong>Lên kế hoạch doanh số và lợi nhuận tháng/ tuần/ ngày</strong></p>\n<p>Phác thảo và quản lý kế hoạch doanh số và lợi nhuận theo từng chu kỳ thời gian nhất định để đảm bảo hoạt động kinh doanh hiệu quả.</p>
                <p><strong>Quản lý chi phí khuyến mãi theo chỉ tiêu yêu cầu</strong></p>
                <p>Điều chỉnh và quản lý chi phí khuyến mãi theo các chỉ tiêu và yêu cầu được đặt ra, đảm bảo tối ưu hóa hiệu quả chi phí.</p>
                <p><strong>Thực hiện các công việc khác theo yêu cầu của cấp trên</strong></p>
                <p>Hoàn thành các nhiệm vụ khác theo yêu cầu và chỉ đạo từ cấp trên để hỗ trợ hoạt động của công ty.</p>","salary" => 2000000,"industry" => "Kinh doanh","field" => "Thực phẩm","internship_duration" => 10,"internship_method" => "online","internship_type" => "parttime","recruitment_number" => 17,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 4,"title" => "Thực tập Sale","description" => "<p><strong>Tìm kiếm, nghiên cứu thị trường.</strong></p>\n<p>Thực hiện tìm kiếm và nghiên cứu thị trường để hiểu rõ hơn về nhu cầu và xu hướng của khách hàng.</p>
                <p><strong>Tư vấn, mở điểm</strong></p>
                <p>Tư vấn và mở ra các cơ hội, chiến lược mới để phát triển kinh doanh.</p>
                <p><strong>Hướng dẫn, hỗ trợ công cụ bán hàng cho đối tác như banner/poster/hình ảnh sản phẩm</strong></p>
                <p>Đưa ra hướng dẫn và cung cấp hỗ trợ về công cụ bán hàng như banner, poster, hình ảnh sản phẩm cho đối tác để tăng hiệu quả bán hàng.</p>","salary" => 3000000,"industry" => "Tư vấn","field" => "Thực phẩm","internship_duration" => 2,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 22,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 4,"title" => "Thực tập Tiếp Thị Mô Hình","description" => "<p><strong>Tư vấn, giới thiệu mô hình Sendo Farm ‘’ĐI CHỢ ONLINE’’ đến nhóm đối tượng tiềm năng</strong></p>\n<p>Tư vấn và giới thiệu mô hình Sendo Farm 'ĐI CHỢ ONLINE' đến nhóm đối tượng tiềm năng để tạo ra sự nhận biết và tăng doanh số.</p>
                <p><strong>Tham gia tổ chức các chương trình khuyến mãi và duy trì hỗ trợ khách hàng trong khu vực được phân công để thúc đẩy tăng doanh số</strong></p>
                <p>Tham gia tổ chức các chương trình khuyến mãi và duy trì hỗ trợ khách hàng trong khu vực được giao để thúc đẩy tăng doanh số bán hàng.</p>","salary" => 4000000,"industry" => "Tư vấn","field" => "Thực phẩm","internship_duration" => 1,"internship_method" => "hybrid","internship_type" => "parttime","recruitment_number" => 19,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 5,"title" => "Thực tập Kế Toán Tổng Hợp Phụ Trách","description" => "<p><strong>Kiểm soát đối chiếu và chịu trách nhiệm với số liệu chi tiết và tổng hợp về Thuế - Nội Bộ.</strong></p>\n<p>Chịu trách nhiệm kiểm soát và đối chiếu số liệu chi tiết và tổng hợp về Thuế - Nội Bộ, đảm bảo tính chính xác.</p>
                <p><strong>Cân đối, hạch toán lương, BHXH, chi phí phát sinh một cách hợp lý</strong></p>
                <p>Thực hiện cân đối, hạch toán lương, BHXH và các chi phí phát sinh một cách hợp lý theo quy định.</p>
                <p><strong>Theo dõi quản lý khấu hao tài sản, phân bổ chi phí</strong></p>
                <p>Theo dõi và quản lý khấu hao tài sản, phân bổ chi phí theo quy định để đảm bảo sự hiệu quả và minh bạch trong quản lý tài chính.</p>","salary" => 5000000,"industry" => "Kế toán","field" => "Dược phẩm","internship_duration" => 3,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 15,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 5,"title" => "Thực tập Digital Marketing","description" => "<p><strong>Lập kế hoạch, triển khai và theo dõi quảng cáo sản phẩm, dịch vụ của Công ty trên các kênh Online: Google, Facebook, Zalo</strong></p>\n<p>Phác thảo kế hoạch, triển khai và theo dõi chiến lược quảng cáo sản phẩm, dịch vụ của công ty trên các nền tảng Online như Google, Facebook, Zalo.</p>
                <p><strong>Nắm rõ kỹ thuật của từng kênh digital để tối ưu hóa nội dung, hình ảnh và chất lượng quảng cáo.</strong></p>
                <p>Hiểu rõ về kỹ thuật của từng kênh digital để tối ưu hóa nội dung, hình ảnh và chất lượng quảng cáo trên các nền tảng này.</p>
                <p><strong>Phát triển các kênh quảng cáo mới trên nền tảng digital</strong></p>
                <p>Xây dựng và phát triển các kênh quảng cáo mới trên các nền tảng digital nhằm mục tiêu mở rộng phạm vi tiếp cận khách hàng.</p>
                <p><strong>Phối hợp với các phòng ban liên quan để đảm bảo tiến độ công việc và kết quả đề ra.</strong></p>
                <p>Hợp tác chặt chẽ với các phòng ban liên quan để đảm bảo tiến độ và kết quả của công việc theo mục tiêu đã đề ra.</p>","salary" => 6000000,"industry" => "Marketing","field" => "Dược phẩm","internship_duration" => 5,"internship_method" => "online","internship_type" => "parttime","recruitment_number" => 20,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 5,"title" => "Thực tập Kế Toán Phụ Trách Kho Dược","description" => "Quản lý Xuất - Nhập - Tồn kho hàng hóa gồm : Thuốc - TBYT - TPCN ...\nKiểm tra hàng hóa ( số lô, hạn dùng) trước khi nhập kho, sắp sếp hàng hóa  gọn gàng theo từng nhóm.
                Nhận đơn hàng, lập chứng từ và xuất hàng theo đơn ( số lô,hạn dùng gần đến hạn xuất trước).
                Kiểm tra thường xuyên các lô hàng gần hết hạn sử dụng, báo cáo tổng hợp xuất nhập tồn kho.","salary" => 5000000,"industry" => "Kế toán","field" => "Dược phẩm","internship_duration" => 7,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 21,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 6,"title" => "Thực tập Kinh doanh","description" => "<p><strong>Quản lý Xuất - Nhập - Tồn kho hàng hóa gồm : Thuốc - TBYT - TPCN ...</strong></p>\n<p>Chịu trách nhiệm quản lý quá trình xuất - nhập - tồn kho hàng hóa bao gồm thuốc, thiết bị y tế và sản phẩm chăm sóc sức khỏe khác.</p>
                <p><strong>Kiểm tra hàng hóa ( số lô, hạn dùng) trước khi nhập kho, sắp sếp hàng hóa  gọn gàng theo từng nhóm.</strong></p>
                <p>Thực hiện kiểm tra hàng hóa (số lô, hạn dùng) trước khi nhập kho và sắp xếp hàng hóa một cách gọn gàng theo từng nhóm để dễ dàng quản lý.</p>
                <p><strong>Nhận đơn hàng, lập chứng từ và xuất hàng theo đơn ( số lô,hạn dùng gần đến hạn xuất trước).</strong></p>
                <p>Chịu trách nhiệm nhận đơn hàng, lập chứng từ và xuất hàng theo đơn (số lô, hạn dùng gần đến hạn xuất trước) để đảm bảo hàng hóa luôn đảm bảo chất lượng.</p>
                <p><strong>Kiểm tra thường xuyên các lô hàng gần hết hạn sử dụng, báo cáo tổng hợp xuất nhập tồn kho.</strong></p>
                <p>Thực hiện kiểm tra định kỳ các lô hàng gần hết hạn sử dụng và lập báo cáo tổng hợp về quá trình xuất nhập tồn kho.</p>","salary" => 5000000,"industry" => "Kinh doanh","field" => "Logistics","internship_duration" => 3,"internship_method" => "hybrid","internship_type" => "parttime","recruitment_number" => 19,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 6,"title" => "Thực tập kế toán","description" => "<p><strong>Thu thập và xử lý các chứng từ số liệu, chứng từ kế toán thông qua các nghiệp vụ kinh tế</strong></p>\n<p>Thực hiện việc thu thập và xử lý các chứng từ số liệu, chứng từ kế toán thông qua các hoạt động kinh tế để đảm bảo tính chính xác và đầy đủ.</p>
                <p><strong>Hạch toán thu/ chi, các khoản khấu hao, ghi chép thuế GTGT/ TNDN,...</strong></p>
                <p>Chịu trách nhiệm hạch toán các giao dịch thu/chi, các khoản khấu hao và ghi chép thuế GTGT/TNDN để bảo đảm tuân thủ quy định và chính sách thuế.</p>
                <p><strong>Theo dõi và quản lý công nợ</strong></p>
                <p>Thực hiện việc theo dõi và quản lý công nợ để đảm bảo quy trình thanh toán diễn ra đúng hạn và hiệu quả.</p>","salary" => 4000000,"industry" => "kế toán","field" => "Logistics","internship_duration" => 6,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 24,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 6,"title" => "Thực tập Kinh Doanh ","description" => "<p><strong>Tìm kiếm khách hàng có nhu cầu nhập hàng.</strong></p>\n<p>Tìm kiếm và xác định khách hàng có nhu cầu nhập hàng, tiếp cận để tạo cơ hội hợp tác.</p>
                <p><strong>Gọi điện hoặc nhắn tin Zalo tiếp cận các chủ cửa hàng trên Shopee, Lazada, Tiki.</strong></p>
                <p>Liên hệ qua điện thoại hoặc Zalo để tiếp cận các chủ cửa hàng trên các nền tảng TMĐT như Shopee, Lazada, Tiki.</p>
                <p><strong>Liên hệ shop Trung, đàm phán, báo giá và thương lượng cùng khách hàng.</strong></p>
                <p>Liên hệ với các shop Trung, thảo luận, đưa ra báo giá và thương lượng để tìm ra giải pháp tốt nhất cùng khách hàng.</p>
                <p><strong>Tư vấn các giải pháp liên quan đến dịch vụ order hộ, vận chuyển hàng hoá trên sàn TMĐT 1688, Taobao, Alibaba.</strong></p>
                <p>Đưa ra các giải pháp tư vấn về dịch vụ order hộ, vận chuyển hàng hóa trên các sàn TMĐT như 1688, Taobao, Alibaba.</p>","salary" => 5000000,"industry" => "Kinh doanh","field" => "Logistics","internship_duration" => 3,"internship_method" => "online","internship_type" => "fulltime","recruitment_number" => 20,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 7,"title" => "Thực tập Tư Vấn Tuyển Sinh","description" => "<p><strong>Tham gia hoạt động tuyển sinh cho các lớp học tại Hệ thống.</strong></p>\n<p>Tham gia các hoạt động tuyển sinh để quảng bá và đăng ký cho các lớp học tại Hệ thống.</p>
                <p><strong>Giới thiệu và tư vấn về các khóa học TOEIC, Giao tiếp, IELTS, Ms.Hoa Junior, tiếng Anh online,... theo nhu cầu khách hàng</strong></p>
                <p>Giới thiệu và cung cấp thông tin, tư vấn về các khóa học TOEIC, Giao tiếp, IELTS, Ms.Hoa Junior, tiếng Anh online,... theo nhu cầu của khách hàng.</p>
                <p><strong>Chủ động liên hệ với khách hàng tiềm năng theo danh sách được cung cấp sẵn hoặc tự khai thác thông qua điện thoại, email</strong></p>
                <p>Tự chủ động liên hệ với khách hàng tiềm năng theo danh sách có sẵn hoặc thông qua việc khai thác thông tin qua điện thoại, email.</p>","salary" => 5000000,"industry" => "Tư vấn","field" => "Giáo dục","internship_duration" => 5,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 23,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 7,"title" => "Thực tập PHP","description" => "<p><strong>Phát triển các ứng dụng web trên nền PHP</strong></p>\n<p>Tạo ra và phát triển các ứng dụng web sử dụng nền tảng PHP.</p>
                <p><strong>Phân tích và đưa ra các giải pháp kỹ thuật cho các dự án của Tổng công ty được giao</strong></p>
                <p>Phân tích và cung cấp các giải pháp kỹ thuật cho các dự án của Tổng công ty theo yêu cầu.</p>
                <p><strong>Triển khai các dự án phần mềm nội bộ</strong></p>
                <p>Thực hiện triển khai các dự án phần mềm nội bộ theo quy định và yêu cầu của công ty.</p>
                <p><strong>Thực hiện các công việc từ Trưởng phòng, Giám đốc Công nghệ.</strong></p>
                <p>Hoàn thành các nhiệm vụ được giao từ Trưởng phòng, Giám đốc Công nghệ theo chỉ đạo.</p>","salary" => 5000000,"industry" => "Công nghệ thông tin","field" => "Giáo dục","internship_duration" => 10,"internship_method" => "hybrid","internship_type" => "parttime","recruitment_number" => 15,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 7,"title" => "Thực tập Chăm Sóc Khách Hàng Online","description" => "<p><strong>Trực page, trả lời toàn bộ tin nhắn của Page, Web, Youtube,...</strong></p>\n<p>Thường xuyên kiểm tra và phản hồi tất cả tin nhắn từ các kênh như Page, Web, Youtube để đảm bảo không bỏ sót thông tin từ khách hàng.</p>
                <p><strong>Đảm bảo không để lỡ tin nhắn của khách hàng</strong></p>
                <p>Chắc chắn rằng không bỏ lỡ bất kỳ tin nhắn nào từ phía khách hàng, đảm bảo phản hồi kịp thời.</p>
                <p><strong>Hàng ngày đi comment vào các bài post trên Facebook, Web, Youtube,...</strong></p>
                <p>Thực hiện việc comment hàng ngày trên các bài đăng trên các nền tảng như Facebook, Web, Youtube để tương tác với khách hàng.</p>
                <p><strong>Tạo ra những nội dung các câu trả lời sáng tạo, phù hợp với các câu hỏi của học viên</strong></p>
                <p>Tạo ra các nội dung câu trả lời sáng tạo và phù hợp với các câu hỏi của học viên để cung cấp thông tin một cách đầy đủ và hấp dẫn.</p>","salary" => null,"industry" => "Tư vấn","field" => "Giáo dục","internship_duration" => 7,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 17,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 8,"title" => "Thực tập Kinh doanh","description" => "<p><strong>Gặp gỡ, tiếp xúc khách hàng tìm hiểu thông tin, báo cáo, đề xuất cấp quản lý các phương án kinh doanh phù hợp.</strong></p>\n<p>Tiếp xúc với khách hàng để hiểu thông tin, báo cáo và đề xuất các phương án kinh doanh phù hợp, sau đó báo cáo cấp quản lý.</p>
                <p><strong>Tham gia lập hồ sơ dự thầu, hồ sơ năng lực công ty.</strong></p>
                <p>Tham gia việc lập hồ sơ dự thầu và hồ sơ năng lực của công ty để tham gia các dự án, gói thầu.</p>
                <p><strong>Thực hiện nhiệm vụ được phân công trong quá trình tổ chức các chương trình hội thảo, quảng cáo, quảng bá thương hiệu.</strong></p>
                <p>Hoàn thành các nhiệm vụ được giao trong quá trình tổ chức hội thảo, quảng cáo, và quảng bá thương hiệu theo yêu cầu.</p>","salary" => 4000000,"industry" => "Kinh doanh","field" => "Sinh học","internship_duration" => 6,"internship_method" => "online","internship_type" => "parttime","recruitment_number" => 20,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 8,"title" => "Thực tập Marketing","description" => "<p><strong>Nắm bắt thông tin thị trường về dòng sản phẩm mình phụ trách thông qua điều tra thị trường và làm việc với hãng cung cấp</strong></p>\n<p>Tìm hiểu thông tin thị trường về sản phẩm mình phụ trách qua việc nghiên cứu thị trường và hợp tác với các nhà cung cấp.</p>
                <p><strong>Tổ chức hội thảo, hội nghị nhằm nâng cao kiến thức sản phẩm cho khách hàng.</strong></p>
                <p>Tổ chức các hội thảo, hội nghị nhằm cung cấp kiến thức chi tiết về sản phẩm cho khách hàng.</p>
                <p><strong>Thiết lập và duy trì mối quan hệ tốt với các chuyên gia đầu ngành (KOL), các khách hàng quan trọng liên quan đến các sản phẩm công ty phân phối.</strong></p>
                <p>Xây dựng và duy trì mối quan hệ tốt với các chuyên gia đầu ngành (KOL) và các khách hàng quan trọng liên quan đến sản phẩm của công ty.</p>","salary" => 4000000,"industry" => "Marketing","field" => "Sinh học","internship_duration" => 7,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 20,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 8,"title" => "Thực tập kế toán","description" => "<p><strong>Tiếp nhận thông tin, lập chứng từ hồ sơ kế toán</strong></p>\n<p>Nhận thông tin và lập chứng từ trong hồ sơ kế toán theo quy trình công việc.</p>
                <p><strong>Theo dõi hạch toán, định khoản lên sổ sách</strong></p>
                <p>Theo dõi quá trình hạch toán và việc định khoản lên sổ sách để đảm bảo tính chính xác của dữ liệu.</p>
                <p><strong>Cân đối doanh thu chi phí, lên báo cáo tài chính</strong></p>
                <p>Thực hiện việc cân đối doanh thu chi phí và lập báo cáo tài chính định kỳ.</p>
                <p><strong>Kê khai thuế, quyết toán thuế cuối quý, cuối năm</strong></p>
                <p>Thực hiện kê khai và quyết toán thuế cuối quý, cuối năm theo quy định của pháp luật thuế.</p>
                <p><strong>Hỗ trợ trưởng nhóm làm việc với cơ quan thuế, bảo hiểm.</strong></p>
                <p>Giúp đỡ trưởng nhóm trong việc làm việc với cơ quan thuế, bảo hiểm khi cần thiết.</p>","salary" => 4000000,"industry" => "kế toán","field" => "Sinh học","internship_duration" => 5,"internship_method" => "hybrid","internship_type" => "parttime","recruitment_number" => 24,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 9,"title" => "Thực tập Kinh doanh","description" => "<p><strong>Liên hệ với khách hàng tiềm năng có sẵn và chủ động tìm kiếm thêm khách hàng bên ngoài để giới thiệu sản phẩm, dịch vụ của công ty.</strong></p>\n<p>Liên hệ với khách hàng tiềm năng hiện có và tìm kiếm thêm khách hàng bên ngoài để giới thiệu sản phẩm, dịch vụ của công ty.</p>
                <p><strong>Thiết lập lịch làm việc, gặp gỡ đàm phán trực tiếp với doanh nghiệp, cá nhân</strong></p>
                <p>Xây dựng lịch làm việc và tổ chức cuộc gặp gỡ đàm phán trực tiếp với các doanh nghiệp, cá nhân liên quan.</p>
                <p><strong>Đàm phán, thuyết phục khách sử dụng sản phẩm, dịch vụ của công ty.</strong></p>
                <p>Thực hiện quá trình đàm phán và thuyết phục khách hàng sử dụng sản phẩm, dịch vụ của công ty.</p>
                <p><strong>Demo, thuyết trình, hướng dẫn khách hàng dùng thử sản phẩm.</strong></p>
                <p>Tổ chức các buổi demo, thuyết trình, và hướng dẫn khách hàng sử dụng thử sản phẩm để tạo sự hiểu biết và tin tưởng.</p>","salary" => 4000000,"industry" => "Kinh doanh","field" => "Mỹ phẩm","internship_duration" => 3,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 13,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 9,"title" => "Thực tập Marketing","description" => "<p><strong>Phát triển chiến lược doanh thu và chiến dịch tiếp thị</strong></p>\n<p>Đề xuất và triển khai chiến lược tăng doanh thu cùng các chiến dịch tiếp thị hiệu quả.</p>
                <p><strong>Theo dõi hoạt động bán hàng và báo cáo</strong></p>
                <p>Theo dõi các hoạt động bán hàng và tạo báo cáo để đánh giá hiệu quả.</p>
                <p><strong>Duy trì cơ sở dữ liệu khách hàng</strong></p>
                <p>Bảo quản và cập nhật thông tin trong cơ sở dữ liệu khách hàng để duy trì mối quan hệ.</p>
                <p><strong>Quảng bá và bán sản phẩm và dịch vụ của công ty</strong></p>
                <p>Tổ chức chiến dịch quảng bá và bán sản phẩm, dịch vụ của công ty để tạo ra doanh số.</p>
                <p><strong>Duy trì và mở rộng cơ sở dữ liệu phản hồi của khách hàng</strong></p>
                <p>Phát triển và mở rộng cơ sở dữ liệu phản hồi từ khách hàng để cải thiện chất lượng dịch vụ.</p>","salary" => 3000000,"industry" => "Marketing","field" => "Mỹ phẩm","internship_duration" => 6,"internship_method" => "online","internship_type" => "parttime","recruitment_number" => 8,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 10,"title" => "Thực tập kinh doanh","description" => "<p><strong>Tư vấn và thiết kế giải pháp tài chính phù hợp để hoàn thiện kế hoạch tương lai của khách hàng: Hưu trí, dự phòng rủi ro, du lịch, đầu tư, du học,...</strong></p>\n<p>Đề xuất và thiết kế các giải pháp tài chính phù hợp giúp khách hàng hoàn thiện kế hoạch tương lai, bao gồm hưu trí, dự phòng rủi ro, du lịch, đầu tư, du học,...</p>
                <p><strong>Đảm bảo chất lượng dịch vụ thông qua việc chăm sóc, hỗ trợ toàn diện</strong></p>
                <p>Đảm bảo chất lượng dịch vụ thông qua việc chăm sóc và hỗ trợ toàn diện về thủ tục hợp đồng, giải đáp thắc mắc, khiếu nại và cung cấp thông tin cần thiết.</p>
                <p><strong>Thực hiện báo cáo kinh doanh cá nhân và đề xuất giải pháp nhằm nâng cao hiệu quả bán hàng.</strong></p>
                <p>Thực hiện báo cáo về kinh doanh cá nhân và đề xuất giải pháp nhằm cải thiện hiệu quả bán hàng.</p>
                <p><strong>Tích cực tham gia các hoạt động đào tạo, huấn luyện khi có yêu cầu.</strong></p>
                <p>Tham gia tích cực các hoạt động đào tạo, huấn luyện để nâng cao kiến thức và kỹ năng khi có yêu cầu.</p>","salary" => 5000000,"industry" => "Kinh doanh","field" => "Bảo hiểm","internship_duration" => 7,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 8,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 10,"title" => "Thực tập kế toán","description" => "<p><strong>Kiểm tra đối chiếu số liệu giữa các đơn vị nội bộ, dữ liệu chi tiết và tổng hợp</strong></p>\n<p>Thực hiện kiểm tra đối chiếu số liệu giữa các đơn vị nội bộ, dữ liệu chi tiết và tổng hợp.</p>
                <p><strong>Kiểm tra hạch toán các định khoản các nghiệp vụ phát sinh</strong></p>
                <p>Đảm bảo kiểm tra hạch toán đúng các định khoản trong các nghiệp vụ phát sinh.</p>
                <p><strong>Kiểm tra sự cân đối giữa các số liệu kế toán chi tiết và tổng hợp</strong></p>
                <p>Đảm bảo kiểm tra sự cân đối giữa các số liệu kế toán chi tiết và tổng hợp.</p>
                <p><strong>Kiểm tra số dư cuối kỳ có hợp lý và khớp đúng với báo cáo chi tiết</strong></p>
                <p>Đảm bảo kiểm tra số dư cuối kỳ có hợp lý và khớp đúng với báo cáo chi tiết.</p>","salary" => 4000000,"industry" => "Kinh doanh","field" => "Bảo hiểm","internship_duration" => 6,"internship_method" => "offline","internship_type" => "parttime","recruitment_number" => 2,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 11,"title" => "Thực tập kinh doanh bất động sản","description" => "<p><strong>Tìm kiếm và khai thác khách hàng.</strong></p>\n<p>Tìm kiếm và khai thác khách hàng thông qua các hoạt động mɑrketing online & offline để xây dựng mối quan hệ.</p>
                <p><strong>Cung cấp thông tin các sản phẩm và dự án của công ty tới khách hàng.</strong></p>
                <p>Thông tin về các sản phẩm và dự án của công ty được cung cấp đến khách hàng.</p>
                <p><strong>Chăm sóc khách hàng hiện tại và khách hàng tiềm năng.</strong></p>
                <p>Chăm sóc khách hàng hiện có và tiềm năng để duy trì và phát triển mối quan hệ.</p>","salary" => 5000000,"industry" => "Kinh doanh","field" => "Bất động sản","internship_duration" => 6,"internship_method" => "online","internship_type" => "parttime","recruitment_number" => 5,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 11,"title" => "Thực tập marketing","description" => "<p><strong>Lập kế hoạch chiến lược xây dựng, duy trì và bảo vệ hình ảnh thương hiệu.</strong></p>\n<p>Xây dựng kế hoạch chiến lược để xây dựng, duy trì và bảo vệ hình ảnh thương hiệu của công ty.</p>
                <p><strong>Lập kế hoạch marketing cho các dự án DXMT triển khai kinh doanh</strong></p>
                <p>Đề xuất và lập kế hoạch marketing cho các dự án DXMT trong quá trình triển khai kinh doanh.</p>","salary" => 6000000,"industry" => "Marketing","field" => "Bất động sản","internship_duration" => 6,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 5,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 12,"title" => "Thực tập tư vấn ","description" => "<p><strong>Tư vấn và bán sản phẩm dịch vụ cố định - di động của mạng Viettel qua tổng đài Viettel.</strong></p>\n<p>Tư vấn và bán các gói data, gói phút gọi, chuyển đổi trả sau cho khách hàng thông qua tổng đài Viettel.</p>
                <p><strong>Gọi ra ngoài, tiếp cận khách hàng</strong></p>
                <p>Tiếp cận khách hàng theo danh sách có sẵn, gửi thông tin về chương trình khuyến mãi và thuyết phục khách hàng đăng ký các gói dịch vụ.</p>","salary" => null,"industry" => "Tư vấn","field" => "Quảng cáo","internship_duration" => 6,"internship_method" => "online","internship_type" => "parttime","recruitment_number" => 3,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 12,"title" => "Thực tập digital marketing","description" => "<p><strong>Lập kế hoạch Digital marketing</strong></p>\n<p>Lập kế hoạch Digital marketing không chỉ đơn giản là việc phát triển một tài liệu. Đó là quá trình kết hợp chiến lược phát triển thương hiệu và kinh doanh thành những hành động cụ thể, nhằm đẩy mạnh hiệu suất và hiệu quả của chiến dịch.</p>
                <p><strong>Theo dõi và triển khai chiến dịch</strong></p>
                <p>Quá trình theo dõi và triển khai kế hoạch Digital marketing không chỉ dừng lại ở việc thực hiện mà còn bao gồm việc đánh giá, điều chỉnh để đảm bảo các hoạt động như SEO, Social marketing, Forum seeding, Website, Email marketing, Mobile marketing, v.v. diễn ra theo kế hoạch.</p>
                <p>Cụ thể hơn, việc triển khai hoạt động quảng cáo trên Google Ads, GDN và các nền tảng khác không chỉ đòi hỏi sự tỉ mỉ trong việc thiết lập mà còn đòi hỏi khả năng tối ưu hóa chiến lược và nguồn lực cho mỗi chiến dịch.</p>","salary" => 5000000,"industry" => "Marketing","field" => "Quảng cáo","internship_duration" => 8,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 6,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 13,"title" => "Thực tập hành chính nhân sự","description" => "<p><strong>Tổ chức và quản lý công tác nhân sự</strong></p>\n<p>Tổ chức và quản lý các công việc nhân sự như tiếp nhận nhân sự, hợp đồng lao động, bổ nhiệm, đánh giá hiệu suất làm việc.</p>
                <p><strong>Xây dựng nội qui và qui trình an toàn lao động</strong></p>
                <p>Xây dựng nội qui, qui trình, qui chế liên quan đến an toàn lao động, phòng cháy chữa cháy, bảo mật và quản lý rủi ro của nhà máy.</p>","salary" => 4000000,"industry" => "Hành chính","field" => "Logistics","internship_duration" => 6,"internship_method" => "offline","internship_type" => "parttime","recruitment_number" => 3,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 13,"title" => "Thực tập bán hàng","description" => "<p><strong>Hướng dẫn và chăm sóc khách hàng</strong></p>\n<p>Quá trình hướng dẫn và chăm sóc khách hàng không chỉ đơn thuần là việc chào đón. Nó còn bao gồm việc tận tâm hướng dẫn khách hàng sử dụng dịch vụ một cách chuyên nghiệp và thân thiện.</p>
                <p>Tiếp nhận order từ khách hàng không chỉ dừng lại ở việc ghi chép. Điều quan trọng là đưa order đồ uống, thức ăn tới bếp với sự chính xác và nhanh nhẹn để đảm bảo sự hài lòng của khách hàng với thời gian chờ đợi.</p>
                <p>Việc mang món ăn lên bàn không chỉ là một bước đơn giản. Nó còn là cơ hội để tạo ra trải nghiệm tốt nhất cho khách hàng, từ cách trình bày món ăn cho đến sự phục vụ ân cần.</p>
                <p>Và cuối cùng, kiểm tra sự hài lòng của khách hàng không chỉ đơn thuần là một bước để hoàn tất giao dịch. Đó là cơ hội để cải thiện dịch vụ, đáp ứng tốt hơn nhu cầu của khách hàng trong tương lai.</p>","salary" => 3000000,"industry" => "Kinh doanh","field" => "Logistics","internship_duration" => 6,"internship_method" => "offline","internship_type" => "fulltime","recruitment_number" => 4,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 14,"title" => "Thực tập editor video","description" => "<p><strong>Edit và biên tập video ngắn</strong></p>\n<p>Việc edit và biên tập video ngắn không chỉ đơn thuần là quá trình cắt ghép. Đó là quá trình kết hợp ý tưởng về thời trang và gia dụng với đội ngũ, tạo ra những video thú vị và sáng tạo.</p>
                <p>Thiết kế hình ảnh và banner không chỉ đơn giản là việc tạo ra hình ảnh đẹp. Nó còn là quá trình tương tác, tạo sự chú ý và thu hút đối tượng mục tiêu trong các chiến dịch sản phẩm.</p>
                <p>Việc kết hợp với đội ngũ Media không chỉ đơn giản là việc làm việc cùng nhau. Đó là quá trình hợp tác, tận dụng mọi nguồn lực để thúc đẩy chiến dịch truyền thông marketing một cách hiệu quả nhất.</p>","salary" => null,"industry" => "Kinh doanh","field" => "Thời trang","internship_duration" => 5,"internship_method" => "online","internship_type" => "fulltime","recruitment_number" => 4,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["business_id" => 14,"title" => "Thực tập viết content","description" => "<p><strong>Thiết kế hình ảnh và bài đăng trên các nền tảng mạng xã hội</strong></p>\n<p>Việc thiết kế hình ảnh và bài đăng không chỉ là công việc đơn thuần tạo hình ảnh và text. Đó còn là quá trình tạo ra những thông điệp sâu sắc và thu hút trên mạng xã hội.</p>
                <p>Thiết kế banner và ấn phẩm cho các chiến dịch được giao không chỉ dừng lại ở việc tạo ra hình ảnh đẹp mắt. Nó còn phải thể hiện đúng thông điệp, gây ấn tượng và kích thích sự quan tâm từ cộng đồng mạng.</p>
                <p>Viết kịch bản cho video quảng bá sản phẩm trên TikTok, Reels là một công việc đòi hỏi sự sáng tạo và hiểu biết sâu sắc về nền tảng đó. Đây là cơ hội để tạo ra những video thu hút, gây chú ý và lan tỏa thông điệp một cách hiệu quả.</p>
                <p>Đọc voice off cho các nội dung cần thu âm và viết nội dung quảng bá không chỉ là việc đọc văn bản. Đó là quá trình tạo ra giọng đọc phù hợp và nội dung thú vị, kèm theo sự nắm bắt tốt về thông điệp cần truyền đạt.</p>","salary" => 4000000,"industry" => "Kinh doanh","field" => "Thời trang","internship_duration" => 7,"internship_method" => "online","internship_type" => "parttime","recruitment_number" => 8,"is_closed" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))]
        ]);
    }
}
