<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('reviews')->insert([
            ["reviewer_id" => 9,"title" => "Không nên thực tập ở công ty DCORP TOÀN CẦU","review_text" => "Dưới sự lãnh đạo của một người quản lý có tiêu chuẩn cao, môi trường làm việc tại công ty đề cao sự nỗ lực và cam kết. Điều này thường tạo ra áp lực khá lớn đối với nhân viên, đôi khi buộc họ phải làm thêm giờ (OT) để hoàn thành công việc đúng thời hạn. Tuy nhiên, những thách thức này cũng đồng đi với cơ hội phát triển cá nhân, với việc học hỏi và rèn luyện kỹ năng quản lý thời gian, đồng thời giúp nâng cao khả năng làm việc dưới áp lực.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 15,"title" => "Phù hợp với người mới ra trường FPT","review_text" => "Công ty thường tham gia vào nhiều dự án lớn, mở ra cơ hội cho nhân viên tương tác trực tiếp với khách hàng. Tuy nhiên, trong quá trình phát triển này, việc chú trọng đến chế độ phúc lợi và quan tâm đến sức khỏe, tinh thần của nhân viên cũng cần được xem xét kỹ lưỡng hơn. Sự cân nhắc này không chỉ tạo điều kiện tốt hơn cho nhân viên thể hiện năng lực mà còn giúp duy trì sự cân bằng giữa công việc và cuộc sống cá nhân.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 10,"title" => "DCORP TOÀN CẦU Cơ sở vật chất tốt, OT nhiều","review_text" => "Tại nơi làm việc này, không gian làm việc được thiết kế rộng rãi, với các khu vực căng tin mở, tạo điều kiện thuận lợi cho sự sáng tạo và giao lưu giữa các nhóm. Tuy nhiên, mặc dù có thời gian làm thêm giờ (OT), nhưng công ty không tính tiền cho việc làm thêm này. Điều này có thể gây ra một số thách thức cho nhân viên, nhưng cũng tạo ra cơ hội để họ linh hoạt quản lý thời gian và cân nhắc giữa công việc và cuộc sống cá nhân một cách hợp lý.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 8,"title" => "Môi trường làm việc giúp học được nhiều thứ IMAP","review_text" => "Tại nơi làm việc này, không chỉ có môi trường làm việc tích cực mà còn có đồng nghiệp vui vẻ, thân thiện. Công ty thường tổ chức nhiều hoạt động kết nối giữa các thành viên trong tổ chức, tạo điều kiện để họ gắn kết và tạo ra môi trường làm việc hòa đồng. Điều này cũng đồng thời mở ra nhiều loại dự án khác nhau, tạo cơ hội cho nhân viên tham gia và phát triển kỹ năng chuyên môn cũng như mối quan hệ xã hội trong môi trường làm việc.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 3,"title" => "Phù hợp với người muốn làm việc ổn định Sam Sung","review_text" => "Công việc tại đây được xác định rõ ràng và có sự đào tạo chuyên sâu, giúp nhân viên nắm vững nhiệm vụ của mình. Tuy nhiên, phong cách làm việc có thể hơi cồng kềnh hoặc quá cấu trúc, đôi khi có thể gây ra sự hạn chế trong việc linh hoạt và sáng tạo. Điều này có thể tạo ra một số rào cản đối với việc thích nghi nhanh chóng với những tình huống linh hoạt và đòi hỏi sự sáng tạo trong công việc hàng ngày.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 14,"title" => "Cơ sở vật chất đẹp, môi trường làm việc năng động IMAP","review_text" => "Tại nơi làm việc này, không chỉ có môi trường làm việc tích cực mà còn có đồng nghiệp vui vẻ, hòa đồng, tạo ra không khí làm việc thoải mái và tràn đầy năng lượng tích cực. Đồng thời, cơ sở vật chất tại đây cũng được đầu tư và chăm sóc kỹ lưỡng, với không gian làm việc sang trọng và hiện đại, tạo điều kiện thuận lợi cho sự sáng tạo và tập trung vào công việc.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 5,"title" => "Công ty tốt để làm việc lâu dài FPT","review_text" => "Tại FPT, có nhiều dự án quy mô lớn, liên quan đến công nghệ mới, mở ra cơ hội cho nhân viên tiếp cận và làm việc trên những nền tảng công nghệ tiên tiến. Đồng thời, hệ thống hỗ trợ cho nhân viên làm việc tại FPT cũng được chú trọng, giúp họ có môi trường làm việc thuận lợi và hiệu quả hơn.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 2,"title" => "HR thiếu chuyên nghiệp","review_text" => "Việc gửi email hỏi về kết quả thực tập và nhận được phản hồi sau hai tuần có thể tạo cảm giác chờ đợi lâu và không hiệu quả trong quá trình tìm kiếm thông tin. Đồng thời, thái độ của phòng nhân sự (HR) có thể khiến người phỏng vấn cảm thấy bị coi thường, điều này có thể ảnh hưởng đến trải nghiệm của người xin việc và gây thiếu hứng thú hoặc không hài lòng trong quá trình tương tác.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 9,"title" => "Công ty tốt cho sinh viên mới ra trường PRUDENTIAL VIỆT NAM","review_text" => "Tại nơi làm việc này, không chỉ có môi trường làm việc thoải mái mà còn tạo cơ hội học hỏi lớn. Đồng thời, đồng nghiệp ở đây thường rất thân thiện và hỗ trợ nhau, tạo điều kiện tốt cho sự phát triển cá nhân và một môi trường làm việc tràn ngập sự sẻ chia và hỗ trợ.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 13,"title" => "Công ty DCORP TOÀN CẦU phù hợp cho người muốn rèn luyện kĩ năng ","review_text" => "Tại đây, đồng nghiệp không chỉ vui vẻ mà còn hỗ trợ nhau một cách nhiệt tình. Mặc dù có thời gian làm thêm giờ (OT) khá nhiều, nhưng công ty đảm bảo trả lương đầy đủ cho những giờ làm việc thêm, tạo điều kiện thuận lợi cho nhân viên cân nhắc giữa công việc và cuộc sống cá nhân một cách linh hoạt.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 16,"title" => "Kế toán thiếu chuyên nghiệp","review_text" => "Việc chậm trả lương mà không có thông báo trước đây đã tạo ra một số bất tiện cho nhân viên tại VPS. Điều này không chỉ ảnh hưởng đến mặt tài chính cá nhân mà còn gây ra sự bất an và không chắc chắn trong quá trình quản lý tài chính cá nhân. Việc không có thông báo trước khiến cho việc lập kế hoạch và quản lý tài chính cá nhân trở nên khó khăn hơn, đặc biệt là khi nhân viên dựa vào lịch trả lương để chi tiêu hàng tháng hoặc định kỳ. Điều này có thể tạo ra sự bất mãn và không hài lòng trong lòng nhân viên, đồng thời ảnh hưởng đến môi trường làm việc và tinh thần làm việc của họ.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 17,"title" => "Ổn cho người mới ra trường VPS","review_text" => "Mức lương trong lĩnh vực Công nghệ thông tin (IT) tại đây được đánh giá là ổn so với mặt bằng chung của thị trường. Điều này tạo điều kiện thuận lợi cho nhân viên trong việc cảm thấy công bằng và đánh giá cao sự đóng góp của mình. Bên cạnh đó, sự xuất hiện của nhiều khách hàng từ châu Âu đến khu vực Châu Á cũng tạo ra cơ hội lớn cho sự phát triển cá nhân và chuyên môn của những người làm việc trong ngành này. Điều này không chỉ mở rộng mạng lưới quan hệ chuyên môn mà còn tạo ra cơ hội tiếp cận với các dự án quốc tế, góp phần nâng cao trình độ và kinh nghiệm của nhân viên.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 1,"title" => "Môi trường làm việc tốt","review_text" => "Tại nơi làm việc này, quy trình làm việc được thiết lập rõ ràng, giúp mọi người dễ dàng nắm bắt và thực hiện công việc một cách hiệu quả. Sếp có tư duy lãnh đạo tích cực và hỗ trợ nhân viên, tạo ra một môi trường làm việc tích cực và động viên nhân viên để họ phát triển tốt nhất trong công việc của mình. Sự hỗ trợ và sự vui vẻ, hòa đồng giữa các thành viên trong tổ chức cũng tạo điều kiện thuận lợi cho sự hợp tác và đổi mới trong công việc hàng ngày.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 3,"title" => "Lương thấp so với mặt bằng chung PRUDENTIAL VIỆT NAM","review_text" => "Tại nơi làm việc này, môi trường làm việc được tạo điều kiện để nhân viên cảm thấy thoải mái và tự do trong công việc. Tuy nhiên, mức lương ở đây có thể được đánh giá thấp so với mặt bằng chung của ngành hoặc so với các công ty cùng lĩnh vực. Điều này có thể tạo ra một số bất tiện cho nhân viên và gây ra sự bất mãn về mặt tài chính, đặc biệt khi so sánh với mức lương trung bình của ngành này.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 13,"title" => "VPS Sếp tuyệt vời","review_text" => "Môi trường năng động, học hỏi từ những người đi trước: Tại đây, không chỉ có môi trường làm việc năng động mà còn là nơi tạo điều kiện cho việc học hỏi liên tục từ những người có kinh nghiệm và thành công trong lĩnh vực. Sự chia sẻ kiến thức và kinh nghiệm giữa các thành viên trong tổ chức tạo nên một không gian phát triển vững mạnh cho sự nghiệp cá nhân.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 20,"title" => "Không hài lòng Xinh Xinh","review_text" => "Nhiều thử thách trong công việc, OT nhiều, lương thấp: Mặc dù có nhiều cơ hội đối mặt với các thử thách trong công việc, việc làm thêm giờ (OT) thường xuyên có thể tạo ra một tình trạng làm việc áp lực hơn và đòi hỏi sự hy sinh thời gian cá nhân. Tuy nhiên, mức lương không phản ánh đầy đủ sự cống hiến và nỗ lực của nhân viên, gây ra sự bất mãn trong mặt tài chính.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 9,"title" => "Nơi tốt để bắt đầu VPS","review_text" => "Đồng nghiệp hòa đồng, vui vẻ, cơ sở vật chất tốt: Môi trường làm việc không chỉ tạo điều kiện để hòa đồng và vui vẻ mà còn đầu tư vào cơ sở vật chất, tạo điều kiện thuận lợi cho công việc hàng ngày. Sự hỗ trợ và sự chia sẻ giữa đồng nghiệp làm tăng tính gắn kết trong tổ chức.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 20,"title" => "Khá ổn so với mặt bằng chung","review_text" => "Sếp tận tình, chu đáo, đồng nghiệp thân thiện, trình độ cao: Sự tận tâm và quan tâm từ sếp không chỉ tạo động lực mà còn giúp xây dựng một môi trường làm việc đầy đồng lòng và chuyên nghiệp. Đồng nghiệp với trình độ cao và thái độ thân thiện làm tăng tính chất lượng và hiệu suất công việc.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 9,"title" => "Công ty tốt cho người mới","review_text" => "Quy trình rõ ràng, đào tạo bài bản, OT có thưởng rõ ràng: Được định hình bởi các quy trình làm việc rõ ràng và sự đào tạo chuyên sâu, nhân viên không chỉ có thể nắm rõ nhiệm vụ mà còn có cơ hội nhận thưởng cho công sức làm thêm giờ (OT), tạo động lực cho sự nỗ lực và hiệu suất cá nhân.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 4,"title" => "Có thể gắn bó lâu dài FPT","review_text" => "Công ty IT lớn, quy trình làm việc rõ ràng, nhiều chương trình hoạt động gắn kết: Với vị thế của một công ty IT lớn, môi trường làm việc không chỉ thúc đẩy sự phát triển chuyên môn mà còn tạo ra nhiều cơ hội tham gia các hoạt động gắn kết, giúp mở rộng mối quan hệ và tạo nền tảng cho sự phát triển cá nhân và sự hòa nhập trong cộng đồng công ty.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 10,"title" => "Không quá xuất sắc nhưng mọi thứ ổn PRUDENTIAL VIỆT NAM","review_text" => "Chỗ làm việc rộng rãi, tiện nghi. Đầy đủ tiện ích: Nơi làm việc được thiết kế với không gian rộng rãi và tiện nghi, cung cấp đầy đủ các tiện ích để nhân viên có thể làm việc hiệu quả. Từ các khu vực làm việc linh hoạt cho đến các khu vực nghỉ ngơi hay tiện ích như phòng họp, khu vực ẩm thực và giải trí, tất cả đều được chăm sóc và phục vụ nhằm tạo ra một môi trường làm việc thoải mái và tích cực.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 2,"title" => "Phù hợp với sinh viên. Nên cẩn thận nếu làm việc lâu dài","review_text" => "Mọi thứ trung bình khá. Có cơ hội tiếp xúc dự án lớn, môi trường chuyên nghiệp, lương lậu trung bình đủ xài: Mặc dù mọi thứ ở đây không nổi bật nhưng vẫn đáp ứng được các tiêu chí cần thiết cho một môi trường làm việc ổn định. Có cơ hội tham gia vào các dự án lớn, đồng thời môi trường chuyên nghiệp và lương lậu ở mức trung bình có thể đảm bảo đủ chi phí sinh hoạt hàng ngày.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 6,"title" => "Môi trường OK Sam Sung","review_text" => "Quy trình và tài liệu rõ ràng. Văn phòng đẹp, bãi đỗ xe rộng, có căng tin lớn: Công ty đặt sự chú trọng vào việc xây dựng quy trình làm việc rõ ràng và cung cấp tài liệu hỗ trợ đầy đủ, giúp nhân viên dễ dàng tiếp cận thông tin và thực hiện công việc một cách hiệu quả. Ngoài ra, văn phòng được thiết kế đẹp mắt, có bãi đỗ xe rộng rãi và căng tin lớn, tạo điều kiện thuận lợi cho môi trường làm việc và sự thoải mái của nhân viên.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 14,"title" => "Đồng nghiệp vui vẻ IMAP","review_text" => "Văn phòng rộng, máy móc thiết bị hiện đại, nhưng lương thực tập hơi thấp so với mặt bằng chung: Với không gian rộng lớn và trang thiết bị hiện đại, công ty đáp ứng được nhu cầu làm việc hiện đại của nhân viên. Tuy nhiên, mức lương thực tập có thể không phản ánh đầy đủ giá trị công việc của thực tập sinh, gây ra sự bất mãn trong mặt tài chính so với mức lương trung bình của ngành.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 6,"title" => "Tuyển thực tập nhưng không đào tạo IMAP","review_text" => "Đồng nghiệp vui vẻ, hòa đồng. Cần lên kế hoạch đào tạo thực tập rõ ràng: Đồng nghiệp ở đây không chỉ là vui vẻ mà còn hòa đồng và hỗ trợ nhau. Tuy nhiên, việc lên kế hoạch đào tạo cho thực tập sinh có thể cần được cải thiện để đảm bảo rằng họ nhận được sự hướng dẫn và hỗ trợ cần thiết để phát triển trong công việc của mình.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 3,"title" => "Cơ sở vật chất hơi tệ","review_text" => "Đồng nghiệp vui vẻ nhưng cơ sở vật chất làm việc cũ, chỗ làm việc chật hẹp: Mặc dù có một đội ngũ đồng nghiệp vui vẻ và hòa đồng, nhưng cơ sở vật chất làm việc thường đã cũ, không đáp ứng được các tiêu chí về môi trường làm việc hiện đại. Chỗ làm việc hẹp và chật chội có thể gây ra sự bất tiện trong quá trình làm việc hàng ngày.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 14,"title" => "Môi trường tốt cho người mới IMAP","review_text" => "Quy trình làm việc rõ ràng, sếp và đồng nghiệp thân thiện: Công ty tập trung vào việc xây dựng và duy trì quy trình làm việc rõ ràng, giúp nhân viên dễ dàng tiếp cận thông tin và thực hiện công việc một cách hiệu quả. Sếp và đồng nghiệp thường thân thiện và hỗ trợ lẫn nhau, tạo ra một môi trường làm việc tích cực và hòa đồng.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 11,"title" => "Mức lương trả chưa phù hợp với khối lượng công việc","review_text" => "Nhân viên được làm quen, trải nghiệm mọi thứ mới. Lượng công việc nhiều, thường xuyên phải OT: Các nhân viên thường có cơ hội tiếp xúc với nhiều công việc mới, tạo điều kiện cho sự học hỏi và trải nghiệm đa dạng. Tuy nhiên, lượng công việc nhiều đôi khi buộc họ phải làm thêm giờ (OT) thường xuyên, gây áp lực và ảnh hưởng đến cân bằng giữa công việc và cuộc sống cá nhân.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 3,"title" => "FPT Sếp tốt, đồng nghiệp thân thiện","review_text" => "Nhiều chương trình trải nghiệm, OT hơi nhiều nhưng được trả lương đúng luật: Công ty thường xuyên tổ chức các chương trình trải nghiệm, tạo cơ hội cho nhân viên tham gia các hoạt động ngoại khóa hoặc nâng cao kỹ năng cá nhân. Mặc dù có mức độ làm thêm giờ (OT) khá cao, nhưng việc này được đền bù đúng theo luật lao động, đảm bảo công bằng và minh bạch.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 16,"title" => "Tạm ổn để cày quốc Xinh Xinh","review_text" => "Cơ sở vật chất tốt, nhiều việc để làm: Với cơ sở vật chất tốt, công ty tạo điều kiện thuận lợi cho nhân viên trong quá trình làm việc hàng ngày. Đồng thời, việc có nhiều công việc để làm cũng tạo ra cơ hội phát triển và khám phá nhiều khả năng mới cho nhân viên.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 13,"title" => "Quy trình công ty lằng nhằng, nhiều cấp bậc","review_text" => "Các khâu xử lý cần được cải thiện. Công ty nhiều cấp bậc nên nhân viên thường không có tiếng nói: Một trong những vấn đề cần được giải quyết chính là khâu xử lý công việc, một số quy trình có thể cần được tối ưu hóa để tăng hiệu quả. Đồng thời, sự tồn tại của nhiều cấp bậc trong công ty có thể làm giảm sự linh hoạt và tương tác giữa nhân viên và quản lý, khiến cho tiếng nói của nhân viên không được thể hiện hoặc không đạt đến các quyết định chiến lược.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 1,"title" => "HR thiếu chuyên nghiệp","review_text" => "Mọi người vui vẻ, HR khi liên hệ thì có thái độ thiếu chuyên nghiệp: Mặc dù môi trường làm việc tỏ ra vui vẻ và hòa đồng, tuy nhiên, trong quá trình liên hệ với phòng nhân sự (HR), một số nhân viên gặp phải thái độ không chuyên nghiệp. Điều này có thể tạo cảm giác bất mãn hoặc không thoải mái khi giao tiếp trong quá trình làm việc.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 2,"title" => "Môi trường làm việc thân thiện PRUDENTIAL VIỆT NAM","review_text" => "Đồng nghiệp thân thiện, Quy trình làm việc rõ ràng, môi trường năng động: Sự thân thiện và hỗ trợ từ đồng nghiệp là một điểm sáng trong môi trường làm việc. Quy trình làm việc được thiết lập rõ ràng, giúp nhân viên dễ dàng tiếp cận thông tin và thực hiện công việc một cách hiệu quả. Môi trường làm việc năng động tạo động lực cho sự phát triển cá nhân và sự sáng tạo.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 20,"title" => "Môi trường tốt ","review_text" => "Sếp thân thiện và dễ thương, tạo điều kiện cho nhân viên IT: Sếp tại đây thường xuất hiện với thái độ thân thiện và hỗ trợ, tạo điều kiện thuận lợi cho sự phát triển và làm việc của nhân viên trong lĩnh vực Công nghệ thông tin (IT). Sự hỗ trợ và khích lệ từ sếp có thể giúp tạo động lực và định hình sự nghiệp của nhân viên.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 16,"title" => "Môi trường phù hợp người mới Sam Sung","review_text" => "Học nhiều điều mới trong quy trình làm việc của công ty: Môi trường làm việc tại công ty này tạo cơ hội cho nhân viên học hỏi và trải nghiệm nhiều điều mới trong quy trình làm việc. Điều này có thể thúc đẩy sự phát triển chuyên môn và mở ra những cơ hội mới trong sự nghiệp của họ.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 16,"title" => "Lương hơi thấp so với thị trường PRUDENTIAL VIỆT NAM","review_text" => "Môi trường làm việc nơi đây thường được đánh giá là vui vẻ và hòa đồng, với sự gắn kết và hỗ trợ đầy đủ từ đồng nghiệp. Tuy nhiên, mức độ làm thêm giờ (OT) thường xuyên đôi khi gây ra áp lực công việc và ảnh hưởng đến cân bằng giữa cuộc sống cá nhân và công việc.\nMặt khác, mức lương tại đây có thể được coi là hơi thấp so với mặt bằng chung của ngành hoặc so với các công ty cùng lĩnh vực. Sự bất đồng này có thể tạo ra một số khó khăn và bất tiện trong việc duy trì cuộc sống và đáp ứng các nhu cầu cá nhân. Tuy vậy, không thể phủ nhận rằng môi trường làm việc vẫn giữ được sự hạnh phúc và niềm vui thông qua mối quan hệ đồng nghiệp tốt đẹp.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 10,"title" => "Khá hài lòng Xinh Xinh","review_text" => "Cơ sở vật chất tại nơi làm việc này thường được đánh giá cao với các tiện ích và trang thiết bị tốt, tạo điều kiện thuận lợi cho việc làm việc hàng ngày. Đồng nghiệp thường xuyên tạo ra một môi trường vui vẻ, hòa đồng và hỗ trợ lẫn nhau, tạo nên một tinh thần đoàn kết mạnh mẽ.\nTuy nhiên, mặc dù có những ưu điểm vượt trội này, việc làm thêm giờ (OT) thường xuyên có thể là một điểm tiêu cực. Sự cần thiết của việc làm thêm giờ có thể tạo ra áp lực công việc và ảnh hưởng đến sức khỏe và cân bằng giữa công việc và cuộc sống cá nhân của nhân viên. Điều này có thể tạo ra một số khó khăn trong việc duy trì một lối sống cân đối và hài hòa.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 17,"title" => "Không hài lòng Sam Sung","review_text" => "Mức lương tại nơi làm việc này thường được coi là thấp so với mặt bằng chung của ngành hoặc so với các công ty đồng ngành. Điều này có thể tạo ra một cảm giác bất mãn và khó khăn trong việc đáp ứng các nhu cầu tài chính và duy trì một cuộc sống ổn định.\nViệc làm thêm giờ (OT) thường xuyên có thể là một vấn đề khác đối với nhân viên tại đây. Sự cần thiết của việc OT liên tục có thể tạo ra áp lực công việc lớn và ảnh hưởng tiêu cực đến sức khỏe và cân bằng giữa công việc và cuộc sống cá nhân.
            Thêm vào đó, sếp tại đây thường được mô tả là khó tính, điều này có thể tạo ra một môi trường làm việc căng thẳng và đòi hỏi nhân viên phải đối mặt với áp lực trong quá trình làm việc hàng ngày. Sự khó tính của sếp có thể ảnh hưởng đến tinh thần làm việc và tạo ra một môi trường không thoải mái cho nhân viên.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 16,"title" => "Phù hợp với người Sam Sung","review_text" => "Văn phòng làm việc tại đây thường được mô tả là đẹp và hiện đại, với không gian thiết kế hấp dẫn và trang thiết bị tiện ích, tạo điều kiện thuận lợi và thoải mái cho việc làm việc hàng ngày. Sự chăm chỉ trong việc tạo nên một môi trường làm việc đẳng cấp thể hiện sự quan tâm đến sự thoải mái và hiệu suất làm việc của nhân viên.\nĐồng nghiệp tại đây thường rất nhiệt tình và hỗ trợ lẫn nhau, tạo ra một tinh thần đồng đội mạnh mẽ. Sự sẵn sàng hỗ trợ và làm việc nhóm của đồng nghiệp giúp tạo nên môi trường làm việc tích cực và động viên, thúc đẩy sự phát triển cá nhân và cộng đồng.
            Công ty thường tham gia vào các dự án lớn, điều này có thể tạo ra cơ hội lớn cho nhân viên được tham gia vào các dự án thú vị và phát triển kỹ năng. Tuy nhiên, việc trả lương phù hợp cho nhân viên là một yếu tố quan trọng cần xem xét để đảm bảo công bằng và sự động viên cho nhân viên, đồng thời khuyến khích sự cam kết và hiệu suất làm việc cao hơn từ phía họ.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 18,"title" => "FPT Môi trường làm việc ổn ","review_text" => "Tại nơi làm việc này, việc có một bãi đỗ xe rộng rãi thường được coi là một điểm lợi thế lớn. Sự thuận tiện trong việc đậu xe giúp giảm bớt áp lực và tạo sự thoải mái cho nhân viên trong quá trình di chuyển đến và rời khỏi nơi làm việc hàng ngày.\nĐồng nghiệp tại đây thường rất nhiệt tình và hỗ trợ lẫn nhau, tạo ra một môi trường làm việc tích cực và đầy năng lượng. Sự sẵn lòng hỗ trợ và làm việc nhóm của đồng nghiệp giúp tạo nên một tinh thần đồng đội mạnh mẽ, tạo động lực cho sự phát triển cá nhân và cộng đồng.
            Mặc dù việc làm thêm giờ (OT) được trả lương đầy đủ, việc có mức độ OT cao thường xuyên có thể tạo ra một số khó khăn đối với nhân viên. Sự cần thiết của việc OT có thể tạo áp lực công việc và ảnh hưởng đến sức khỏe và cân bằng giữa công việc và cuộc sống cá nhân của họ. Điều này có thể tạo ra một số khó khăn trong việc duy trì một lối sống cân đối và hài hòa.","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 11,"title" => "Phù hợp với người mới ","review_text" => "Tại nơi làm việc này, môi trường thường được mô tả là vui vẻ và hòa đồng, với sự giao tiếp tích cực và mối quan hệ tốt đẹp giữa đồng nghiệp. Sự thân thiện và hỗ trợ từ đồng nghiệp giúp tạo ra một môi trường làm việc thoải mái và động viên, thúc đẩy sự phát triển cá nhân và cộng đồng.\nTuy nhiên, mức lương tại đây thường được coi là hơi thấp so với mặt bằng chung của ngành hoặc so với các công ty tương đương. Sự chênh lệch này có thể tạo ra một số khó khăn trong việc duy trì cuộc sống và đáp ứng các nhu cầu cá nhân, gây ra cảm giác bất mãn về mặt tài chính đối với một số nhân viên.
            Mặt khác, quy trình làm việc tại đây thường được xây dựng rõ ràng, với các bước và quy định được thiết lập một cách minh bạch và dễ tiếp cận. Điều này giúp nhân viên dễ dàng tiếp cận thông tin và thực hiện công việc một cách hiệu quả, tăng cường sự hiểu biết và tự tin trong công việc hàng ngày.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 19,"title" => "Môi trường tốt, thoải mái Xinh Xinh","review_text" => "Tại nơi làm việc này, mối quan hệ giữa đồng nghiệp thường được mô tả là vui vẻ và hòa đồng, với sự hỗ trợ và tinh thần đồng đội mạnh mẽ. Sự sẵn sàng hỗ trợ và chia sẻ kiến thức, kinh nghiệm từ đồng nghiệp không chỉ tạo ra một môi trường làm việc tích cực mà còn thúc đẩy sự phát triển chuyên môn và cá nhân.\nSếp tại đây thường được miêu tả là tận tình và chu đáo đối với nhân viên. Sự quan tâm đến sự nghiệp và sự phát triển cá nhân của nhân viên được thể hiện thông qua sự hỗ trợ, lắng nghe và chỉ dẫn từ sếp. Sự tận tâm này không chỉ tạo ra một môi trường làm việc tích cực mà còn giúp xây dựng lòng tin và sự cam kết từ phía nhân viên đối với mục tiêu và giá trị của công ty.","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))]
        ]);
    }
}
