<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('reviews')->insert([
            ["reviewer_id" => 9,"title" => "Không nên thực tập ở công ty DCORP TOÀN CẦU","review_text" => "Sếp khó tính, môi trường làm việc áp lực, nhiều khi phải OT","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 13,"title" => "Phù hợp với người mới ra trường FPT","review_text" => "Nhiều dự án lớn, được làm việc trực tiếp với khách hàng, cần quan tâm hơn đến chế độ phúc lợi của nhân viên","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 19,"title" => "DCORP TOÀN CẦU Cơ sở vật chất tốt, OT nhiều","review_text" => "Môi trường rộng rãi, có căng tin rộng, OT nhưng không được tính tiền","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 13,"title" => "Môi trường làm việc giúp học được nhiều thứ IMAP","review_text" => "Đồng nghiệp vui vẻ, có nhiều hoạt động kết nối, nhiều loại dự án","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 6,"title" => "Phù hợp với người muốn làm việc ổn định Sam Sung","review_text" => "Công việc cụ thể, được đào tạo bài bản, rõ ràng nhưng hơi cồng kềnh","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 10,"title" => "Cơ sở vật chất đẹp, môi trường làm việc năng động IMAP","review_text" => "Đồng nghiệp vui vẻ, hòa đồng, cơ sở vật chất sang trọng","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 15,"title" => "Công ty tốt để làm việc lâu dài FPT","review_text" => "Nhiều dự án lớn, công nghệ mới, hỗ trợ tốt cho nhân viên để làm việc FPT","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 20,"title" => "HR thiếu chuyên nghiệp","review_text" => "Viết email hỏi kết quả xem có được nhận thực tập không thì 2 tuần sau mới trả lời, thái độ HR coi thường người đến phỏng vấn","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 8,"title" => "Công ty tốt cho sinh viên mới ra trường PRUDENTIAL VIỆT NAM","review_text" => "Môi trường thoải mái, học hỏi được nhiều. Đồng nghiệp thân thiện","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 5,"title" => "Công ty DCORP TOÀN CẦU phù hợp cho người muốn rèn luyện kĩ năng ","review_text" => "Đồng nghiệp vui vẻ, support nhiệt tình, OT nhiều nhưng được trả lương đầy đủ","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 8,"title" => "Kế toán thiếu chuyên nghiệp","review_text" => "Chậm lương 1 tuần mà không thông báo gì cho nhân viên VPS","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 11,"title" => "Ổn cho người mới ra trường VPS","review_text" => "Mức lương IT ổn so với mặt bằng chung của thị trường. Nhiều khách hàng từ châu Âu đến Châu Á","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 20,"title" => "Môi trường làm việc tốt","review_text" => "Quy trình làm việc rõ ràng. Sếp tốt, mọi người vui vẻ hỗ trợ nhau trong công việc","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 3,"title" => "Lương thấp so với mặt bằng chung PRUDENTIAL VIỆT NAM","review_text" => "Môi trường làm việc thoải mái,nhưng lương thấp so với  mặt bằng chung","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 13,"title" => "VPS Sếp tuyệt vời","review_text" => "Môi trường năng động, học hỏi được nhiều từ những người đi trước","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 12,"title" => "Không hài lòng Xinh Xinh","review_text" => "Nhiều thử thách trong công việc, OT nhiều, lương thấp","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 20,"title" => "Nơi tốt để bắt đầu VPS","review_text" => "Đồng nghiệp hòa đồng, vui vẻ, cơ sở vật chất tốt","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 5,"title" => "Khá ổn so với mặt bằng chung","review_text" => "Sếp tận tình, chu đáo, đồng nghiệp thân thiện, trình độ cao","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 9,"title" => "Công ty tốt cho người mới","review_text" => "Quy trình rõ ràng. Được đào tạo bài bản. OT sẽ có thưởng rõ ràng","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 11,"title" => "Có thể gắn bó lâu dài FPT","review_text" => "Công ty IT lớn, quy trình làm việc rõ ràng. Có nhiều chương trình hoạt động gắn kết","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 6,"title" => "Không quá xuất sắc nhưng mọi thứ ổn PRUDENTIAL VIỆT NAM","review_text" => "Chỗ làm việc rộng rãi, tiện nghi. Đầy đủ tiện ích","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 17,"title" => "Phù hợp với sinh viên. Nên cẩn thận nếu làm việc lâu dài","review_text" => "Mọi thứ trung bình khá. Có cơ hội tiếp xúc dự án lớn, môi trường chuyên nghiệp, lương lậu trung bình đủ xài","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 15,"title" => "Môi trường OK Sam Sung","review_text" => "Quy trình và tài liệu rõ ràng. Văn phòng đẹp, bãi đỗ xe rộng, có căng tin lớn","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 13,"title" => "Đồng nghiệp vui vẻ IMAP","review_text" => "Văn phòng rộng, máy móc thiết bị hiện đại, nhưng lương thực tập hơi thấp so với mặt bằng chung","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 2,"title" => "Tuyển thực tập nhưng không đào tạo IMAP","review_text" => "Đồng nghiệp vui vẻ, hòa đồng. Cần lên kế hoạc đào tạo thực tập rõ ràng","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 10,"title" => "Cơ sở vật chất hơi tệ","review_text" => "Đồng nghiệp vui vẻ nhưng cơ sở vật chất làm việc cũ, chỗ làm việc chật hẹp","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 18,"title" => "Môi trường tốt cho người mới IMAP","review_text" => "Quy trình làm việc rõ ràng, sếp và đồng nghiệp thân thiện","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 9,"title" => "Mức lương trả chưa phù hợp với khối lượng công việc","review_text" => "Nhân viên được làm quen, trải nghiệm mọi thứ mới. Lượng công việc nhiều, thường xuyên phải OT","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 8,"title" => "FPT Sếp tốt, đồng nghiệp thân thiện","review_text" => "Nhiều chương trình trải nghiệm, OT hơi nhiều nhưng được trả lương đúng luật","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 4,"title" => "Tạm ổn để cày quốc Xinh Xinh","review_text" => "Cơ sở vật chất tốt, nhiều việc để làm","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 4,"title" => "Quy trình công ty lằng nhằng, nhiều cấp bậc","review_text" => "Các khâu xử lý cần được cải thiện. Công ty nhiều cấp bậc nên nhân viên thường không có tiếng nói","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 15,"title" => "HR thiếu chuyên nghiệp","review_text" => "Mọi người vui vẻ, HR khi liên hệ thì có thái độ thiếu chuyên nghiệp","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 9,"title" => "Môi trường làm việc thân thiện PRUDENTIAL VIỆT NAM","review_text" => "Đồng nghiệp thân thiện, Quy trình làm việc rõ ràng, môi trường năng động","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 14,"title" => "Môi trường tốt ","review_text" => "Sếp thân thiện và dễ thương, tạo điều kiện cho nhân viên IT","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 12,"title" => "Môi trường phù hợp người mới Sam Sung","review_text" => "Học nhiều điều mới trong quy trình làm việc của công ty","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 6,"title" => "Lương hơi thấp so với thị trường PRUDENTIAL VIỆT NAM","review_text" => "Mọi người vui vẻ, OT nhiều, lương hơi thấp so với mặt bằng chung","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 3,"title" => "Khá hài lòng Xinh Xinh","review_text" => "Cơ sở vật chất tốt, đồng nghiệp vui vẻ, OT nhiều","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 14,"title" => "Không hài lòng Sam Sung","review_text" => "Lương thấp, OT nhiều, sếp khó tính","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 15,"title" => "Phù hợp với người Sam Sung","review_text" => "Văn phòng đẹp, đồng nghiệp nhiệt tình, dự án lớn, cần trả lương phù hợp cho nhân viên","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 4,"title" => "FPT Môi trường làm việc ổn ","review_text" => "Bãi đỗ xe rộng, đồng nghiệp nhiệt tình, OT có lương đầy đủ nhưng OT  nhiều","is_anonymous" => 0, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 15,"title" => "Phù hợp với người mới ","review_text" => "Mọi người vui vẻ, lương hơi thấp so với mặt bằng chung, quy trình làm việc rõ ràng","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))],
            ["reviewer_id" => 1,"title" => "Môi trường tốt, thoải mái Xinh Xinh","review_text" => "Đồng nghiệp vui vẻ, sếp tận tình, chu đáo","is_anonymous" => 1, "created_at" => Carbon::now()->subHours(rand(1, 1800)), "updated_at" => Carbon::now()->subHours(rand(1, 1800))]
        ]);
    }
}
